In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df_payday = pd.read_csv('input/sales1.csv')

df_payday.head()

C:\Users\dsoli\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Order Date,Order Time,Media,Campaign,Type,Cust No,Name,Sex,Age,Customer Phone,...,Email,Ship Date,State,CompanyId,DID No,Txn Ref/Cheque #,Payment Reference Number,Delivery Date,Carrier,Tracking No
0,1/1/2017,0:54,MCTV InBound,NaN,T,8795159.0,WILBERT ALEXANDER LOPEZ TOLEDO,NaN,NaN,4567-3138-1561,...,NaN,1/2/2017,Sin.,11,NaN,NaN,NaN,1/2/2017,MultiPack (COD),785191602575 | FEDEX
1,1/1/2017,1:57,MCTV InBound,NaN,T,8795203.0,ROSA MARIA GOMEZ GOMEZ,NaN,NaN,4565-6103-7679,...,NaN,1/2/2017,Chih.,11,NaN,NaN,NaN,1/2/2017,UPS (COD),1Z30V80W0416288567 | UPS
2,1/1/2017,2:40,MCTV InBound,NaN,T,8795211.0,PATRICIA ROMERO BELLO,M,NaN,0501-2230-0211,...,NaN,1/2/2017,Pue.,11,NaN,NaN,NaN,1/2/2017,CARSSA (COD),MEXPBC17013644997 | CARSSA
3,1/1/2017,2:40,MCTV InBound,NaN,T,8795211.0,PATRICIA ROMERO BELLO,M,NaN,0501-2230-0211,...,NaN,1/2/2017,Pue.,11,NaN,NaN,NaN,1/2/2017,CARSSA (COD),MEXPBC17013644997 | CARSSA
4,1/1/2017,2:40,MCTV InBound,NaN,T,8795211.0,PATRICIA ROMERO BELLO,M,NaN,0501-2230-0211,...,NaN,1/2/2017,Pue.,11,NaN,NaN,NaN,1/2/2017,CARSSA (COD),MEXPBC17013644997 | CARSSA

In [5]:
list(df_payday)

['Order Date',
 'Order Time',
 'Media',
 'Campaign',
 'Type',
 'Cust No',
 'Name',
 'Sex',
 'Age',
 'Customer Phone',
 'Customer Mobile',
 'Postcode',
 'RFC',
 'Request Send Bill',
 'Agent',
 'Callcenter',
 'Order ref',
 'Order Source',
 'legacy#',
 'Disc Code',
 'Status',
 'Payment',
 'Item',
 'Description',
 'Qty',
 'Value net',
 'P&P net',
 'Invoice Fee',
 'Total net',
 'Family',
 'Item Type',
 'Email',
 'Ship Date',
 'State',
 'CompanyId',
 'DID No',
 'Txn Ref/Cheque #',
 'Payment Reference Number',
 'Delivery Date',
 'Carrier',
 'Tracking No']

In [6]:
info_payday = ['Order Date','Postcode','Status', 'Payment', 'Item', 'Total net', 'Item Type', 'Ship Date', 'State', 'Delivery Date']
df_payday = df_payday[info_payday]
df_payday.head()

,Order Date,Postcode,Status,Payment,Item,Total net,Item Type,Ship Date,State,Delivery Date
0,1/1/2017,80884,Returned,COD,370001MX,3108.0,Main,1/2/2017,Sin.,1/2/2017
1,1/1/2017,32000,Returned,COD,370001MX,3222.0,Main,1/2/2017,Chih.,1/2/2017
2,1/1/2017,72180,Returned,COD,032002MX,2109.0,Main,1/2/2017,Pue.,1/2/2017
3,1/1/2017,72180,Returned,COD,032020MX,114.0,Upsell,1/2/2017,Pue.,1/2/2017
4,1/1/2017,72180,Returned,COD,032025MX,0.0,Upsell,1/2/2017,Pue.,1/2/2017

In [7]:
date_payday_df = df_payday.groupby('Order Date')
date_payday_df.head()

,Order Date,Postcode,Status,Payment,Item,Total net,Item Type,Ship Date,State,Delivery Date
0,1/1/2017,80884,Returned,COD,370001MX,3108.0,Main,1/2/2017,Sin.,1/2/2017
1,1/1/2017,32000,Returned,COD,370001MX,3222.0,Main,1/2/2017,Chih.,1/2/2017
2,1/1/2017,72180,Returned,COD,032002MX,2109.0,Main,1/2/2017,Pue.,1/2/2017
3,1/1/2017,72180,Returned,COD,032020MX,114.0,Upsell,1/2/2017,Pue.,1/2/2017
4,1/1/2017,72180,Returned,COD,032025MX,0.0,Upsell,1/2/2017,Pue.,1/2/2017
344,1/2/2017,9740,Returned,COD,090009MXB,3227.0,Main,1/2/2017,D.F.,1/2/2017
345,1/2/2017,55886,Returned,COD,090009MXB,3227.0,Main,1/2/2017,Edomex.,1/2/2017
346,1/2/2017,55886,Returned,COD,090003MX,228.0,Upsell,1/2/2017,Edomex.,1/2/2017
347,1/2/2017,57460,Shipped,COD,090009MXB,3227.0,Main,1/2/2017,Edomex.,1/2/2017
348,1/2/2017,55749,Returned,COD,090009MXB,3113.0,Main,1/2/2017,Edomex.,1/2/2017
848,1/3/2017,54760,Cancelled,OXXO,370001MX,2995.0,Main,NaN,MEX,NaN
849,1/3/2017,22930,Returned,COD,370001MX,3108.0,Main,1/3/2017,B.C.,1/3/2017
850,1/3/2017,2650,Cancelled,OXXO,250001MX,1999.0,Main,NaN,DIF,NaN
851,1/3/2017,2650,Cancelled,OXXO,250002MX,0.0,Upsell,NaN,DIF,NaN
852,1/3/2017,55749,Cancelled,OXXO,190004MX,299.0,Main,NaN,MEX,NaN
1269,1/4/2017,4319,Shipped,Payworks,090009MXB,3227.0,Main,1/5/2017,D.F.,1/5/2017
1270,1/4/2017,4319,Shipped,Payworks,090003MX,228.0,Upsell,1/5/2017,D.F.,1/5/2017
1271,1/4/2017,1540,Returned,COD,090009MXB,3227.0,Main,1/4/2017,D.F.,1/4/2017
1272,1/4/2017,1540,Returned,COD,090003MX,228.0,Upsell,1/4/2017,D.F.,1/4/2017
1273,1/4/2017,21130,Cancelled,OXXO,370001MX,2995.0,Main,NaN,BCN,NaN
1715,1/5/2017,54170,Returned,COD,370001MX,3222.0,Main,1/5/2017,Edomex.,1/5/2017
1716,1/5/2017,44820,Cancelled,BANK_BANCOMER,370001MX,2995.0,Main,NaN,JAL,NaN
1717,1/5/2017,37180,Returned,COD,370001MX,3222.0,Main,1/5/2017,Gto.,1/5/2017
1718,1/5/2017,44160,Returned,COD,090009MXB,3227.0,Main,1/5/2017,Jal.,1/5/2017
1719,1/5/2017,44160,Returned,COD,090003MX,228.0,Upsell,1/5/2017,Jal.,1/5/2017
2088,1/6/2017,94299,Shipped,Payworks,039059MX,4027.0,Main,1/9/2017,Ver.,1/9/2017
2089,1/6/2017,65260,Shipped,Payworks,090009MXB,3113.0,Main,1/10/2017,N.L.,1/10/2017
2090,1/6/2017,66264,Shipped,Payworks,090009MXB,3227.0,Main,1/10/2017,N.L.,1/10/2017
2091,1/6/2017,66264,Shipped,Payworks,090003MX,228.0,Upsell,1/10/2017,N.L.,1/10/2017
2092,1/6/2017,54409,Shipped,COD,032002MX,827.0,Main,1/6/2017,Edomex.,1/6/2017
...,...,...,...,...,...,...,...,...,...,...
63194,5/13/2017,96730,Shipped,OXXO,370001MX,2995.0,Main,5/16/2017,Veracruz,5/16/2017
63195,5/13/2017,7500,Cancelled,BANK_BANCOMER,370001MX,1497.5,Main,NaN,Distrito Federal,NaN
63196,5/13/2017,64988,Returned,COD,250001MX,1999.0,Main,5/13/2017,Nuevo LeÃ³n,5/13/2017
63197,5/13/2017,21130,Returned,COD,250001MX,2227.0,Main,5/13/2017,Baja California,5/13/2017
63198,5/13/2017,32690,Shipped,COD,250001MX,1999.0,Main,5/13/2017,Chihuahua,5/13/2017
63727,5/14/2017,55707,Shipped,COD,41227,1999.0,Main,5/15/2017,MÃ©xico,5/15/2017
63728,5/14/2017,63737,Cancelled,OXXO,370001MX,1497.5,Main,NaN,Nayarit,NaN
63729,5/14/2017,52300,Shipped,VISA-SSL,370001MX,1497.5,Main,5/15/2017,MÃ©xico,5/15/2017
63730,5/14/2017,63738,Cancelled,OXXO,370001MX,1497.5,Main,NaN,Nayarit,NaN
63731,5/14/2017,99000,Returned,COD,032002MX,827.0,Main,5/15/2017,Zacatecas,5/15/2017
64400,5/15/2017,28067,Returned,COD,039198MXB,3727.0,Main,5/15/2017,Colima,5/15/2017
64401,5/15/2017,84093,Shipped,Payworks,090009MXB,3499.0,Main,5/16/2017,Sonora,5/16/2017
64402,5/15/2017,84093,Shipped,Payworks,090003MX,0.0,Upsell,5/16/2017,Sonora,5/16/2017
64403,5/15/2017,45149,Shipped,Bancomer,090009MXB,3499.0,Main,6/10/2017,Jalisco,6/10/2017
64404,5/15/2017,45149,Shipped,Bancomer,090003MX,0.0,Upsell,6/10/2017,Jalisco,6/10/2017
64693,5/16/2017,72813,Shipped,VISA-SSL,032003MX,1197.0,Misc,5/16/2017,Puebla,5/16/2017
64694,5/16/2017,72813,Shipped,VISA-SSL,032021MX,0.0,Misc,5/16/2017,Puebla,5/16/2017
64695,5/16/2017,42506,Shipped,Payworks,090009MXB,3499.0,Main,5/17/2017,Hidalgo,5/17/2017
64696,5/16/2017,42506,Shipped,Payworks,090003MX,0.0,Upsell,5/17/2017,Hidalgo,5/17/2017
64697,5/16/2017,42506,Shipped,Payworks,350006MX,0.0,Upsell,5/17/2017,Hidalgo,5/17/2017
65035,5/17/2017,45019,Shipped,PAYPAL-SSL,370001MX,2995.0,Main,5/20/2017,Jalisco,5/20/2017
65036,5/17/2017,54470,Returned,COD,032003MX,2109.0,Main,5/18/2017,MÃ©xico,5/18/2017
65037,5/17/2017,54470,Returned,COD,032021MX,114.0,Upsell,5/18/2017,MÃ©xico,5/18/2017
65038,5/17/2017,54470,Returned,COD,032026MX,0.0,Upsell,5/18/2017,MÃ©xico,5/18/2017
65039,5/17/2017,56589,Returned,COD,032002MX,2109.0,Main,5/17/2017,MÃ©xico,5/17/2017
65445,5/18/2017,82180,Shipped,Payworks,032003MX,1895.0,Main,5/22/2017,Sinaloa,5/22/2017
65446,5/18/2017,82180,Shipped,Payworks,032021MX,0.0,Upsell,5/22/2017,Sinaloa,5/22/2017
65447,5/18/2017,82180,Shipped,Payworks,032021MX,0.0,Misc,5/22/2017,Sinaloa,5/22/2017
65448,5/18/2017,63900,Shipped,COD,032003MX,2109.0,Main,5/22/2017,Nayarit,5/22/2017
65449,5/18/2017,63900,Shipped,COD,032021MX,114.0,Upsell,5/22/2017,Nayarit,5/22/2017

In [8]:
Shipped = df_payday['Status'] == 'Shipped'
print(Shipped.head())

0    False
1    False
2    False
3    False
4    False
Name: Status, dtype: bool

In [9]:
shipped_payday_df = df_payday[Shipped]
print(shipped_payday_df.head())

   Order Date Postcode   Status   Payment      Item  Total net Item Type  \
8    1/1/2017    45640  Shipped  Payworks  070003MX     1197.0      Main
9    1/1/2017    45640  Shipped  Payworks  070004MX        0.0    Upsell
15   1/1/2017    27276  Shipped       COD  250001MX     2113.0      Main
16   1/1/2017    27276  Shipped       COD  250002MX      395.0    Upsell
17   1/1/2017    90670  Shipped       COD  250001MX     2227.0      Main

   Ship Date        State Delivery Date
8   1/2/2017  GUADALAJARA      1/2/2017
9   1/2/2017  GUADALAJARA      1/2/2017
15  1/2/2017        Coah.      1/2/2017
16  1/2/2017        Coah.      1/2/2017
17  1/2/2017        Tlax.      1/2/2017

In [45]:
shipped_payday_df.Payment.unique()

array(['Payworks', 'COD', 'PAYPAL-SSL', 'ECMC-SSL', 'Bancomer',
       'BANK_BANCOMER', 'OXXO', 'VISA-SSL', 'Dinero', 'Terminal',
       'Wholesale', 'AMEX-SSL', 'Mercado'], dtype=object)

In [46]:
consumer = shipped_payday_df['Payment'] == 'Wholesale'
print(consumer.head())

8     False
9     False
15    False
16    False
17    False
Name: Payment, dtype: bool

In [49]:
#aqui estoy excluyendo las ventas de mayoreo pero no puedo hacerlo con solo un valor, entonces tambien exclui el valor mercado
mask = shipped_payday_df['Payment'].isin(['Wholesale', 'Mercado'])
shipped_payday_df[~mask]

,Order Date,Postcode,Status,Payment,Item,Total net,Item Type,Ship Date,State,Delivery Date
8,1/1/2017,45640,Shipped,Payworks,070003MX,1197.0,Main,1/2/2017,GUADALAJARA,1/2/2017
9,1/1/2017,45640,Shipped,Payworks,070004MX,0.0,Upsell,1/2/2017,GUADALAJARA,1/2/2017
15,1/1/2017,27276,Shipped,COD,250001MX,2113.0,Main,1/2/2017,Coah.,1/2/2017
16,1/1/2017,27276,Shipped,COD,250002MX,395.0,Upsell,1/2/2017,Coah.,1/2/2017
17,1/1/2017,90670,Shipped,COD,250001MX,2227.0,Main,1/2/2017,Tlax.,1/2/2017
24,1/1/2017,5330,Shipped,Payworks,280001MX,3594.0,Main,1/2/2017,D.F.,1/2/2017
25,1/1/2017,14400,Shipped,Payworks,250001MX,2227.0,Main,1/2/2017,D.F.,1/2/2017
26,1/1/2017,14400,Shipped,Payworks,250002MX,395.0,Upsell,1/2/2017,D.F.,1/2/2017
27,1/1/2017,14400,Shipped,Payworks,350006MX,0.0,Upsell,1/2/2017,D.F.,1/2/2017
28,1/1/2017,37128,Shipped,Payworks,280001MX,3594.0,Main,1/2/2017,Gto.,1/2/2017
29,1/1/2017,37128,Shipped,Payworks,350006MX,0.0,Upsell,1/2/2017,Gto.,1/2/2017
30,1/1/2017,91919,Shipped,PAYPAL-SSL,3337303MXB,1599.0,Main,1/2/2017,VER,1/2/2017
31,1/1/2017,77516,Shipped,Payworks,280001MX,3594.0,Main,1/2/2017,Q.Roo.,1/2/2017
32,1/1/2017,77516,Shipped,Payworks,280002MX,499.0,Upsell,1/2/2017,Q.Roo.,1/2/2017
33,1/1/2017,75040,Shipped,COD,370001MX,3222.0,Main,1/2/2017,Pue.,1/2/2017
34,1/1/2017,79930,Shipped,Payworks,090009MXB,2999.0,Main,1/2/2017,S.L.P.,1/2/2017
35,1/1/2017,79930,Shipped,Payworks,090003MX,0.0,Upsell,1/2/2017,S.L.P.,1/2/2017
36,1/1/2017,89319,Shipped,COD,090009MXB,3113.0,Main,1/2/2017,TAMAULIPAS,1/2/2017
37,1/1/2017,89319,Shipped,COD,090003MX,114.0,Upsell,1/2/2017,TAMAULIPAS,1/2/2017
40,1/1/2017,52680,Shipped,COD,250001MX,2227.0,Main,1/2/2017,Edomex.,1/2/2017
41,1/1/2017,52680,Shipped,COD,RushMX,49.0,Upsell,1/2/2017,Edomex.,1/2/2017
42,1/1/2017,52680,Shipped,COD,250002MX,395.0,Upsell,1/2/2017,Edomex.,1/2/2017
47,1/1/2017,72290,Shipped,Payworks,090009MXB,2999.0,Main,1/2/2017,Pue.,1/2/2017
48,1/1/2017,72290,Shipped,Payworks,090003MX,0.0,Upsell,1/2/2017,Pue.,1/2/2017
49,1/1/2017,72290,Shipped,Payworks,350006MX,0.0,Upsell,1/2/2017,Pue.,1/2/2017
50,1/1/2017,34000,Shipped,Payworks,280001MX,3494.0,Main,1/2/2017,Dgo.,1/2/2017
51,1/1/2017,34000,Shipped,Payworks,350006MX,0.0,Upsell,1/2/2017,Dgo.,1/2/2017
52,1/1/2017,50220,Shipped,COD,250001MX,2227.0,Main,1/2/2017,Edomex.,1/2/2017
53,1/1/2017,50220,Shipped,COD,250002MX,395.0,Upsell,1/2/2017,Edomex.,1/2/2017
54,1/1/2017,79300,Shipped,Payworks,370001MX,3222.0,Main,1/2/2017,S.L.P.,1/2/2017
...,...,...,...,...,...,...,...,...,...,...
65496,5/18/2017,66636,Shipped,Payworks,090009MXB,3499.0,Main,5/19/2017,NUEVO LEON,5/19/2017
65497,5/18/2017,66636,Shipped,Payworks,090003MX,0.0,Upsell,5/19/2017,NUEVO LEON,5/19/2017
65498,5/18/2017,3610,Shipped,COD,090009MXB,3613.0,Main,5/18/2017,Ciudad de MÃ©xico,5/18/2017
65499,5/18/2017,3610,Shipped,COD,090003MX,114.0,Upsell,5/18/2017,Ciudad de MÃ©xico,5/18/2017
65502,5/18/2017,62588,Shipped,COD,052003MX,3113.0,Main,5/18/2017,Morelos,5/18/2017
65503,5/18/2017,69005,Shipped,COD,090009MXB,3149.1,Main,5/18/2017,Oaxaca,5/18/2017
65504,5/18/2017,69005,Shipped,COD,090003MX,0.0,Upsell,5/18/2017,Oaxaca,5/18/2017
65505,5/18/2017,85280,Shipped,Payworks,090009MXB,3499.0,Main,5/19/2017,SONORA,5/19/2017
65506,5/18/2017,85280,Shipped,Payworks,090003MX,0.0,Upsell,5/19/2017,SONORA,5/19/2017
65507,5/18/2017,85280,Shipped,Payworks,350006MX,0.0,Upsell,5/19/2017,SONORA,5/19/2017
65508,5/18/2017,35059,Shipped,COD,032003MX,2109.0,Main,5/22/2017,Durango,5/22/2017
65509,5/18/2017,35059,Shipped,COD,032021MX,114.0,Upsell,5/22/2017,Durango,5/22/2017
65510,5/18/2017,35059,Shipped,COD,032021MX,0.0,Misc,5/22/2017,Durango,5/22/2017
65511,5/18/2017,31940,Shipped,COD,370001MX,2694.6,Main,5/18/2017,Chihuahua,5/18/2017
65515,5/18/2017,67112,Shipped,BANK_BANCOMER,032036MX,1197.0,Ordinary,5/18/2017,Nuevo LeÃ³n,5/18/2017
65516,5/18/2017,67112,Shipped,BANK_BANCOMER,070005MX,0.0,Upsell,5/18/2017,Nuevo LeÃ³n,5/18/2017
65517,5/18/2017,36584,Shipped,COD,41227,2113.0,Main,5/18/2017,GUANAJUATO,5/18/2017
65518,5/18/2017,55018,Shipped,COD,032002MX,713.0,Main,5/18/2017,MÃ©xico,5/18/2017
65519,5/18/2017,44970,Shipped,COD,370001MX,2727.0,Main,5/18/2017,Jalisco,5/18/2017
65520,5/18/2017,44970,Shipped,COD,WARANTYMX!,69.0,Upsell,5/18/2017,Jalisco,5/18/2017
65521,5/18/2017,66260,Shipped,Bancomer,250001MX,1999.0,Main,5/19/2017,Nuevo LeÃ³n,5/19/2017
65522,5/18/2017,66260,Shipped,Bancomer,2500021MXB,694.0,Upsell,5/19/2017,Nuevo LeÃ³n,5/19/2017
65523,5/18/2017,24156,Shipped,OXXO,370001MX,1497.5,Main,5/19/2017,Campeche,5/19/2017
65524,5/18/2017,35158,Shipped,OXXO,032003MX,1197.0,Misc,5/23/2017,Durango,5/23/2017
65525,5/18/2017,35158,Shipped,OXXO,070005MX,0.0,Upsell,5/23/2017,Durango,5/23/2017
65526,5/18/2017,35158,Shipped,OXXO,032003MX,0.0,Misc,5/23/2017,Durango,5/23/2017
65527,5/18/2017,35158,Shipped,OXXO,032021MX,0.0,Misc,5/23/2017,Durango,5/23/2017
65528,5/18/2017,53100,Shipped,Payworks,290001MX,1999.0,Main,5/23/2017,MÃ‰XICO,5/23/2017
65529,5/18/2017,53100,Shipped,Payworks,350006MX,0.0,Upsell,5/23/2017,MÃ‰XICO,5/23/2017
65530,5/18/2017,37980,Shipped,Bancomer,290001MX,1999.0,Main,5/23/2017,Guanajuato,5/23/2017

In [50]:
consumer_shipped_payday_df = shipped_payday_df[~mask]
consumer_shipped_payday_df.head()

,Order Date,Postcode,Status,Payment,Item,Total net,Item Type,Ship Date,State,Delivery Date
8,1/1/2017,45640,Shipped,Payworks,070003MX,1197.0,Main,1/2/2017,GUADALAJARA,1/2/2017
9,1/1/2017,45640,Shipped,Payworks,070004MX,0.0,Upsell,1/2/2017,GUADALAJARA,1/2/2017
15,1/1/2017,27276,Shipped,COD,250001MX,2113.0,Main,1/2/2017,Coah.,1/2/2017
16,1/1/2017,27276,Shipped,COD,250002MX,395.0,Upsell,1/2/2017,Coah.,1/2/2017
17,1/1/2017,90670,Shipped,COD,250001MX,2227.0,Main,1/2/2017,Tlax.,1/2/2017

In [51]:
shipped_date1 = consumer_shipped_payday_df['Order Date'].str.split('/', 1, expand = True)
shipped_date1.head()

    0       1
8   1  1/2017
9   1  1/2017
15  1  1/2017
16  1  1/2017
17  1  1/2017

In [52]:
shipped_date1.rename(  columns={
    0 : 'month',
    1 : 'day_year'
  },
  inplace=True)
shipped_date1.head()

   month day_year
8      1   1/2017
9      1   1/2017
15     1   1/2017
16     1   1/2017
17     1   1/2017

In [53]:
shipped_date2 = shipped_date1['day_year'].str.split('/', 1, expand = True)
shipped_date2.head()

    0     1
8   1  2017
9   1  2017
15  1  2017
16  1  2017
17  1  2017

In [54]:
shipped_date2.rename(  columns={
    0 : 'day',
    1 : 'year'
  },
  inplace=True)
shipped_date2.head()

   day  year
8    1  2017
9    1  2017
15   1  2017
16   1  2017
17   1  2017

In [55]:
shipped_date3 = shipped_date2.join(shipped_date1, how = 'outer')
shipped_date3.head()

   day  year month day_year
8    1  2017     1   1/2017
9    1  2017     1   1/2017
15   1  2017     1   1/2017
16   1  2017     1   1/2017
17   1  2017     1   1/2017

In [56]:
shipped_date4 = shipped_date3.drop('day_year', axis = 1)
shipped_date4.head()

   day  year month
8    1  2017     1
9    1  2017     1
15   1  2017     1
16   1  2017     1
17   1  2017     1

In [61]:
enriched_shipped_payday_df = consumer_shipped_payday_df.join(shipped_date4,how ='outer')
enriched_shipped_payday_df.head()

,Order Date,Postcode,Status,Payment,Item,Total net,Item Type,Ship Date,State,Delivery Date,day,year,month
8,1/1/2017,45640,Shipped,Payworks,070003MX,1197.0,Main,1/2/2017,GUADALAJARA,1/2/2017,1,2017,1
9,1/1/2017,45640,Shipped,Payworks,070004MX,0.0,Upsell,1/2/2017,GUADALAJARA,1/2/2017,1,2017,1
15,1/1/2017,27276,Shipped,COD,250001MX,2113.0,Main,1/2/2017,Coah.,1/2/2017,1,2017,1
16,1/1/2017,27276,Shipped,COD,250002MX,395.0,Upsell,1/2/2017,Coah.,1/2/2017,1,2017,1
17,1/1/2017,90670,Shipped,COD,250001MX,2227.0,Main,1/2/2017,Tlax.,1/2/2017,1,2017,1

In [62]:
enriched_shipped_payday_df['sales'] = 1
enriched_shipped_payday_df.head()

,Order Date,Postcode,Status,Payment,Item,Total net,Item Type,Ship Date,State,Delivery Date,day,year,month,sales
8,1/1/2017,45640,Shipped,Payworks,070003MX,1197.0,Main,1/2/2017,GUADALAJARA,1/2/2017,1,2017,1,1
9,1/1/2017,45640,Shipped,Payworks,070004MX,0.0,Upsell,1/2/2017,GUADALAJARA,1/2/2017,1,2017,1,1
15,1/1/2017,27276,Shipped,COD,250001MX,2113.0,Main,1/2/2017,Coah.,1/2/2017,1,2017,1,1
16,1/1/2017,27276,Shipped,COD,250002MX,395.0,Upsell,1/2/2017,Coah.,1/2/2017,1,2017,1,1
17,1/1/2017,90670,Shipped,COD,250001MX,2227.0,Main,1/2/2017,Tlax.,1/2/2017,1,2017,1,1

In [68]:
enriched_shipped_payday_df['Payment'].unique()

array(['Payworks', 'COD', 'PAYPAL-SSL', 'ECMC-SSL', 'Bancomer',
       'BANK_BANCOMER', 'OXXO', 'VISA-SSL', 'Dinero', 'Terminal',
       'AMEX-SSL'], dtype=object)

In [69]:
shipped_date_df = enriched_shipped_payday_df.groupby('day')
shipped_date_df.head()

,Order Date,Postcode,Status,Payment,Item,Total net,Item Type,Ship Date,State,Delivery Date,day,year,month,sales
8,1/1/2017,45640,Shipped,Payworks,070003MX,1197.00,Main,1/2/2017,GUADALAJARA,1/2/2017,1,2017,1,1
9,1/1/2017,45640,Shipped,Payworks,070004MX,0.00,Upsell,1/2/2017,GUADALAJARA,1/2/2017,1,2017,1,1
15,1/1/2017,27276,Shipped,COD,250001MX,2113.00,Main,1/2/2017,Coah.,1/2/2017,1,2017,1,1
16,1/1/2017,27276,Shipped,COD,250002MX,395.00,Upsell,1/2/2017,Coah.,1/2/2017,1,2017,1,1
17,1/1/2017,90670,Shipped,COD,250001MX,2227.00,Main,1/2/2017,Tlax.,1/2/2017,1,2017,1,1
347,1/2/2017,57460,Shipped,COD,090009MXB,3227.00,Main,1/2/2017,Edomex.,1/2/2017,2,2017,1,1
350,1/2/2017,23090,Shipped,PAYPAL-SSL,280001MX,2499.00,Main,1/2/2017,BCS,1/2/2017,2,2017,1,1
351,1/2/2017,72090,Shipped,Payworks,552411,4227.00,Main,1/3/2017,Pue.,1/3/2017,2,2017,1,1
352,1/2/2017,52947,Shipped,Payworks,370001MX,3222.00,Main,1/3/2017,Edomex.,1/3/2017,2,2017,1,1
367,1/2/2017,9750,Shipped,Payworks,032003MX,2223.00,Main,1/3/2017,D.F.,1/3/2017,2,2017,1,1
853,1/3/2017,7300,Shipped,Payworks,370001MX,2994.00,Main,1/4/2017,D.F.,1/4/2017,3,2017,1,1
854,1/3/2017,7300,Shipped,Payworks,370001MX,1497.00,Upsell,1/4/2017,D.F.,1/4/2017,3,2017,1,1
856,1/3/2017,88209,Shipped,Payworks,090009MXB,3113.00,Main,1/4/2017,Tamps.,1/4/2017,3,2017,1,1
857,1/3/2017,88209,Shipped,Payworks,090003MX,114.00,Upsell,1/4/2017,Tamps.,1/4/2017,3,2017,1,1
858,1/3/2017,57170,Shipped,Payworks,090009MXB,3227.00,Main,1/4/2017,Edomex.,1/4/2017,3,2017,1,1
1269,1/4/2017,4319,Shipped,Payworks,090009MXB,3227.00,Main,1/5/2017,D.F.,1/5/2017,4,2017,1,1
1270,1/4/2017,4319,Shipped,Payworks,090003MX,228.00,Upsell,1/5/2017,D.F.,1/5/2017,4,2017,1,1
1286,1/4/2017,11700,Shipped,Payworks,032001MX,2223.00,Main,1/5/2017,D.F.,1/5/2017,4,2017,1,1
1287,1/4/2017,11700,Shipped,Payworks,032019MX,228.00,Upsell,1/5/2017,D.F.,1/5/2017,4,2017,1,1
1288,1/4/2017,11700,Shipped,Payworks,032024MX,0.00,Upsell,1/5/2017,D.F.,1/5/2017,4,2017,1,1
1720,1/5/2017,38600,Shipped,Payworks,039198MXB,3227.00,Main,1/9/2017,Gto.,1/9/2017,5,2017,1,1
1721,1/5/2017,23650,Shipped,COD,032003MX,2223.00,Main,1/5/2017,B.C.S.,1/5/2017,5,2017,1,1
1722,1/5/2017,23650,Shipped,COD,032026MX,228.00,Upsell,1/5/2017,B.C.S.,1/5/2017,5,2017,1,1
1723,1/5/2017,23650,Shipped,COD,032021MX,0.00,Upsell,1/5/2017,B.C.S.,1/5/2017,5,2017,1,1
1724,1/5/2017,34179,Shipped,COD,370001MX,3222.00,Main,1/5/2017,Dgo.,1/5/2017,5,2017,1,1
2088,1/6/2017,94299,Shipped,Payworks,039059MX,4027.00,Main,1/9/2017,Ver.,1/9/2017,6,2017,1,1
2089,1/6/2017,65260,Shipped,Payworks,090009MXB,3113.00,Main,1/10/2017,N.L.,1/10/2017,6,2017,1,1
2090,1/6/2017,66264,Shipped,Payworks,090009MXB,3227.00,Main,1/10/2017,N.L.,1/10/2017,6,2017,1,1
2091,1/6/2017,66264,Shipped,Payworks,090003MX,228.00,Upsell,1/10/2017,N.L.,1/10/2017,6,2017,1,1
2092,1/6/2017,54409,Shipped,COD,032002MX,827.00,Main,1/6/2017,Edomex.,1/6/2017,6,2017,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14057,1/26/2017,88776,Shipped,Payworks,090009MXB,3227.00,Main,1/27/2017,Tamps.,1/27/2017,26,2017,1,1
14058,1/26/2017,88776,Shipped,Payworks,090003MX,228.00,Upsell,1/27/2017,Tamps.,1/27/2017,26,2017,1,1
14059,1/26/2017,75480,Shipped,Payworks,090009MXB,2900.61,Main,1/27/2017,Pue.,1/27/2017,26,2017,1,1
14060,1/26/2017,75480,Shipped,Payworks,090003MX,0.00,Upsell,1/27/2017,Pue.,1/27/2017,26,2017,1,1
14061,1/26/2017,75480,Shipped,Payworks,RushMX,47.39,Upsell,1/27/2017,Pue.,1/27/2017,26,2017,1,1
14530,1/27/2017,54753,Shipped,COD,032003MX,2223.00,Main,1/27/2017,Edomex.,1/27/2017,27,2017,1,1
14531,1/27/2017,54753,Shipped,COD,032026MX,228.00,Upsell,1/27/2017,Edomex.,1/27/2017,27,2017,1,1
14532,1/27/2017,54753,Shipped,COD,032020MX,0.00,Upsell,1/27/2017,Edomex.,1/27/2017,27,2017,1,1
14539,1/27/2017,7420,Shipped,Payworks,090009MXB,2999.00,Main,1/30/2017,D.F.,1/30/2017,27,2017,1,1
14540,1/27/2017,7420,Shipped,Payworks,090003MX,0.00,Upsell,1/30/2017,D.F.,1/30/2017,27,2017,1,1
14982,1/28/2017,80060,Shipped,OXXO,250001MX,1999.00,Main,1/30/2017,SIN,1/30/2017,28,2017,1,1
14983,1/28/2017,80060,Shipped,OXXO,250002MX,0.00,Upsell,1/30/2017,SIN,1/30/2017,28,2017,1,1
14985,1/28/2017,32674,Shipped,Payworks,039198MXB,3113.00,Main,1/30/2017,Chih.,1/30/2017,28,2017,1,1
14986,1/28/2017,32674,Shipped,Payworks,350006MX,99.50,Upsell,1/30/2017,Chih.,1/30/2017,28,2017,1,1
14987,1/28/2017,62010,Shipped,Payworks,039198MXB,3227.00,Main,1/30/2017,Mor.,1/30/2017,28,2017,1,1
15976,1/29/2017,9410,Shipped,Payworks,032002MX,599.00,Main,1/30/2017,D.F.,1/30/2017,29,2017,1,1
15977,1/29/2017,9410,Shipped,Payworks,350006MX,0.00,Upsell,1/30/2017,D.F.,1/30/2017,29,2017,1,1
15978,1/29/2017,9410,Shipped,Payworks,032020MX,599.00,Main,1/30/2017,D.F.,1/30/2017,29,2017,1,1
15979,1/29/2017,50020,Shipped,COD,370001MX,3222.00,Main,1/30/2017,Edomex.,1/30/2017,29,2017,1,1
15980,1/29/2017,11000,Shipped,Payworks,090009MXB,3113.00,Main,2/1/2017,D.F.,2/1/2017,29,2017,1,1
17023,1/30/2017,31100,Shipped,Payworks,280001MX,2915.05,Main,1/31/2017,Chih.,1/31/2017,30,2017,1,1
17024,1/30/2017,31100,Shipped,Payworks,330002MX,291.11,Upsell,1/31/2017,Chih.,1/31/2017,30,2017,1,1
17025,1/30/2017,31100,Shipped,Payworks,280002MX,485.84,Upsell,1/31/2017,Chih.,1/31/2017,30,2017,1,1
17026,1/30/2017,31100,Shipped,Payworks,350006MX,0.00,Upsell,1/31/2017,Chih.,1/31/2017,30,2017,1,1
17033,1/30/2017,7300,Shipped,Payworks,250002MX,827.00,Main,1/31/2017,D.F.,1/31/2017,30,2017,1,1
17432,1/31/2017,72543,Shipped,OXXO,039198MXB,3400.38,Main,2/2/2017,Pue.,2/2/2017,31,2017,1,1
17433,1/31/2017,72543,Shipped,OXXO,090003MX,0.00,Upsell,2/2/2017,Pue.,2/2/2017,31,2017,1,1
17434,1/31/2017,72543,Shipped,OXXO,RushMX,47.62,Upsell,2/2/2017,Pue.,2/2/2017,31,2017,1,1
17435,1/31/2017,72543,Shipped,OXXO,350006MX,0.00,Upsell,2/2/2017,Pue.,2/2/2017,31,2017,1,1
17442,1/31/2017,14600,Shipped,COD,370001MX,3222.00,Main,1/31/2017,D.F.,1/31/2017,31,2017,1,1

In [72]:
grouped_day_df = enriched_shipped_payday_df.groupby('day')
grouped_day_df.aggregate(np.sum)

      Total net  sales
day
1    1572714.38   1189
10   1357958.02   1042
11   2007965.18   1486
12   1949908.97   1445
13   1604317.08   1215
14   1918156.86   1480
15   1837993.28   1388
16   1314714.80   1008
17   1415371.73    953
18   1720696.96   1264
19   1688636.50   1272
2    1481269.90   1088
20   1114776.15    877
21   1519199.75   1114
22   1735524.19   1308
23   1379714.16   1010
24   1086787.40    842
25   1713678.15   1318
26   1755972.25   1345
27   1179747.49    864
28   1444581.71   1128
29   1389223.10   1082
3    1282165.72    971
30    887494.12    685
31    425868.65    316
4    1832324.28   1355
5    2051788.01   1491
6    1591430.15   1190
7    1851738.95   1385
8    1893190.31   1427
9    1561099.65   1141

In [65]:
#aqui quisiera graficar dia vs sales pero no puedo
grouped_day_df.plot(kind='line',x='day',y='sales')
plt.show()

KeyError: 'day'

In [66]:
year_2017 = enriched_shipped_payday_df['year'] == '2017'
print(year_2017.head())

8     True
9     True
15    True
16    True
17    True
Name: year, dtype: bool

In [67]:
#aqui quiero repetir lo que hice con shipped en fechas para poder graficar 2017 y 2018 x separado y asi ver si hay cambio en tendencia en ambos pero no me deja hacer lo mismo. Quizas porque como estoy usando el placeholder de base que solo tiene datos del 2017
year_2017_df = enriched_shipped_payday_df[2017]
year_2017_df.head()

KeyError: 2017

In [73]:
#aqui quiero hacer segmentos de precio para poder ver si el comportamiento es distinto dependiendo de la gama de precio de la compra
enriched_shipped_payday_df.max()

Order Date         5/9/2017
Status              Shipped
Payment            VISA-SSL
Item             WARANTYMX!
Total net             39984
Item Type            Upsell
Ship Date          9/9/2017
State               morelos
Delivery Date      9/9/2017
day                       9
year                   2017
month                     5
sales                     1
dtype: object

In [74]:
enriched_shipped_payday_df.min()

Order Date                1/1/2017
Status                     Shipped
Payment                   AMEX-SSL
Item                      002003MX
Total net                        0
Item Type                     Main
Ship Date                1/10/2017
State            ACAPULCO GUERRERO
Delivery Date            1/10/2017
day                              1
year                          2017
month                            1
sales                            1
dtype: object

In [75]:
enriched_shipped_payday_df.mean()

Total net    1333.165387
sales           1.000000
dtype: float64

In [77]:
#aqui tratando de hacer tiers
enriched_shipped_payday_df['Very Low'] = np.where(enriched_shipped_payday_df['Total net']<=200, 'yes', 'no')
enriched_shipped_payday_df.head()

,Order Date,Postcode,Status,Payment,Item,Total net,Item Type,Ship Date,State,Delivery Date,day,year,month,sales,Very Low
8,1/1/2017,45640,Shipped,Payworks,070003MX,1197.0,Main,1/2/2017,GUADALAJARA,1/2/2017,1,2017,1,1,no
9,1/1/2017,45640,Shipped,Payworks,070004MX,0.0,Upsell,1/2/2017,GUADALAJARA,1/2/2017,1,2017,1,1,yes
15,1/1/2017,27276,Shipped,COD,250001MX,2113.0,Main,1/2/2017,Coah.,1/2/2017,1,2017,1,1,no
16,1/1/2017,27276,Shipped,COD,250002MX,395.0,Upsell,1/2/2017,Coah.,1/2/2017,1,2017,1,1,no
17,1/1/2017,90670,Shipped,COD,250001MX,2227.0,Main,1/2/2017,Tlax.,1/2/2017,1,2017,1,1,no

In [83]:
#no hallo como meter una condicional con dos elementos
enriched_shipped_payday_df['Low'] = np.where(enriched_shipped_payday_df['Total net']>200 and enriched_shipped_payday_df['Total net']<=400, 'yes', 'no')
enriched_shipped_payday_df.head()

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().